before_script:
- apt-get update -qy
- apt-get install -y libsndfile1
- pip install tox

python36:
  image: python:3.6
  script:
  - tox -e py36
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

python37:
  image: python:3.7
  script:
  - tox -e py37
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
